<?php

use App\Http\Controllers\ApiAccessController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CannedImageController;
use App\Http\Controllers\CustomFieldController;
use App\Http\Controllers\MailboxConnectionController;
use App\Http\Controllers\MailboxPollingController;
use App\Http\Controllers\MailPolicyController;
use App\Http\Controllers\MailSafetyController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\RecoveryController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TicketWorkflowController;
use App\Http\Controllers\TrackingController;
use App\Http\Controllers\TranslationController;
use App\Http\Controllers\WorkflowController;
use App\Http\Controllers\WorkspaceController;
use Illuminate\Support\Facades\Route;

Route::prefix('api/v1')->group(function () {
    Route::get('session', [AuthController::class, 'session']);
    Route::post('setup', [AuthController::class, 'setup'])->middleware('throttle:5,1');
    Route::post('login', [AuthController::class, 'login'])->middleware('throttle:5,1');
    Route::post('forgot-password', [RecoveryController::class, 'forgot'])->middleware('throttle:5,1,forgot-password');
    Route::post('reset-password', [RecoveryController::class, 'reset'])->middleware('throttle:5,1,reset-password');
    Route::middleware('auth')->group(function () {
        Route::post('mailboxes/poll', MailboxPollingController::class)->middleware('throttle:10,1');
        Route::get('translation/config', [TranslationController::class, 'config']);
        Route::put('translation/settings', [TranslationController::class, 'settings']);
        Route::put('tickets/{ticket}/language', [TranslationController::class, 'language']);
        Route::put('tickets/{ticket}/subject-translation', [TranslationController::class, 'subject']);
        Route::put('messages/{message}/translation', [TranslationController::class, 'message']);
        Route::post('messages/{message}/prepare-translation', [TranslationController::class, 'prepare']);
        Route::get('workflows', [WorkflowController::class, 'index']);
        Route::post('workflows/{kind}', [WorkflowController::class, 'save']);
        Route::put('workflows/{kind}/{id}', [WorkflowController::class, 'save'])->whereNumber('id');
        Route::delete('workflows/{kind}/{id}', [WorkflowController::class, 'destroy'])->whereNumber('id');
        Route::get('mail-policy', [MailPolicyController::class, 'index']);
        Route::put('mail-policy/settings', [MailPolicyController::class, 'settings']);
        Route::post('mail-policy/senders', [MailPolicyController::class, 'sender']);
        Route::post('mail-policy/suppressions', [MailPolicyController::class, 'suppress']);
        Route::delete('mail-policy/{kind}/{id}', [MailPolicyController::class, 'destroy'])->whereNumber('id');
        Route::get('api-keys', [ApiAccessController::class, 'index']);
        Route::post('api-keys', [ApiAccessController::class, 'store']);
        Route::delete('api-keys/{key}', [ApiAccessController::class, 'revoke'])->whereNumber('key');
        Route::get('tickets/{ticket}/history', [TicketWorkflowController::class, 'history']);
        Route::post('tickets/{ticket}/merge', [TicketWorkflowController::class, 'merge']);
        Route::post('tickets/{ticket}/macros/{macro}', [TicketWorkflowController::class, 'applyMacro'])->whereNumber('macro');
        Route::get('tickets/{ticket}/follow-ups', [TicketWorkflowController::class, 'followUps']);
        Route::post('tickets/{ticket}/follow-ups', [TicketWorkflowController::class, 'schedule']);
        Route::delete('tickets/{ticket}/follow-ups/{followUp}', [TicketWorkflowController::class, 'cancel'])->whereNumber('followUp');
        Route::post('tickets/{ticket}/inline-images', [TicketWorkflowController::class, 'upload'])->middleware('throttle:30,1');
        Route::get('inline-images/{id}', [TicketWorkflowController::class, 'image'])->whereUuid('id');
        Route::post('canned-images', [CannedImageController::class, 'store'])->middleware('throttle:30,1');
        Route::get('canned-images/{id}', [CannedImageController::class, 'show'])->whereUuid('id');
        Route::get('messages/{message}/delivery', [TicketWorkflowController::class, 'delivery']);
        Route::post('logout', [AuthController::class, 'logout']);
        Route::patch('profile', [AuthController::class, 'profile']);
        Route::get('workspace', [WorkspaceController::class, 'bootstrap']);
        Route::put('settings', [WorkspaceController::class, 'settings']);
        Route::get('custom-fields', [CustomFieldController::class, 'index']);
        Route::put('custom-fields', [CustomFieldController::class, 'update']);
        Route::get('sending-safety', [MailSafetyController::class, 'show']);
        Route::put('sending-safety', [MailSafetyController::class, 'configure']);
        Route::post('sending-safety/pause', [MailSafetyController::class, 'pause']);
        Route::post('sending-safety/resume', [MailSafetyController::class, 'resume']);
        Route::get('reports', [WorkspaceController::class, 'reports']);
        Route::get('activity', [WorkspaceController::class, 'activity']);
        Route::post('mailboxes/{mailbox}/sync', [WorkspaceController::class, 'sync'])->middleware('throttle:10,1');
        Route::post('mailboxes/test-connection', [MailboxConnectionController::class, 'test'])->middleware('throttle:5,1,mailbox-connection');
        Route::post('mailboxes/{mailbox}/test-connection', [MailboxConnectionController::class, 'test'])->middleware('throttle:5,1,mailbox-connection');
        Route::get('tickets', [TicketController::class, 'index']);
        Route::post('tickets', [TicketController::class, 'store']);
        Route::post('tickets/bulk', [TicketController::class, 'bulk']);
        Route::delete('tickets/bulk', [TicketController::class, 'bulkDestroy']);
        Route::get('tickets/{ticket}', [TicketController::class, 'show']);
        Route::patch('tickets/{ticket}', [TicketController::class, 'update']);
        Route::post('tickets/{ticket}/messages', [TicketController::class, 'message']);
        Route::put('tickets/{ticket}/draft', [TicketController::class, 'draft']);
        Route::post('messages/{message}/retry', [TicketController::class, 'retry'])->middleware('throttle:10,1');
        Route::get('attachments/{message}/{index}', [TicketController::class, 'attachment'])->whereNumber('index')->name('attachments.download');
        Route::get('attachments/{message}/{index}/inline', [TicketController::class, 'inlineAttachment'])->whereNumber('index')->name('attachments.inline');
        Route::post('manage/{type}', [WorkspaceController::class, 'save']);
        Route::put('manage/{type}/{id}', [WorkspaceController::class, 'save'])->whereNumber('id');
        Route::delete('manage/{type}/{id}', [WorkspaceController::class, 'destroy'])->whereNumber('id');
    });
});
Route::get('mail/open/{attempt}', [TrackingController::class, 'open'])->middleware(['signed', 'throttle:120,1'])->name('mail.open');
Route::match(['get', 'post'], 'mail/preferences/{attempt}', [TrackingController::class, 'optOut'])->middleware(['signed', 'throttle:30,1'])->name('mail.optout');
Route::get('/', [PageController::class, 'home'])->name('app');
Route::get('/login', [PageController::class, 'auth'])->defaults('mode', 'login')->name('login');
Route::get('/register', [PageController::class, 'auth'])->defaults('mode', 'register')->name('register');
Route::get('/forgot-password', [PageController::class, 'auth'])->defaults('mode', 'forgot')->name('password.request');
Route::get('/reset-password', [PageController::class, 'auth'])->defaults('mode', 'reset')->name('password.reset');
Route::post('/register', [AuthController::class, 'setup'])->middleware('throttle:5,1');
Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:5,1');
Route::post('/forgot-password', [RecoveryController::class, 'forgot'])->middleware('throttle:5,1,forgot-password');
Route::post('/reset-password', [RecoveryController::class, 'reset'])->middleware('throttle:5,1,reset-password');
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
Route::middleware('auth')->group(function () {
    Route::get('/tickets', [PageController::class, 'show'])->defaults('component', 'Inbox')->name('tickets.index');
    Route::get('/tickets/{id}', [PageController::class, 'show'])->whereNumber('id')->defaults('component', 'Ticket')->name('tickets.show');
    Route::get('/automations', [PageController::class, 'show'])->defaults('component', 'Workflows')->name('automations');
    foreach (['settings', 'replies', 'reports', 'profile', 'activity'] as $page) {
        Route::get('/'.$page, [PageController::class, 'show'])->defaults('component', 'Workspace')->defaults('page', $page)->name($page);
    }
});
