<script setup>
import { ref, reactive, onMounted } from 'vue';
import { state, api, notify } from '../store';
import Modal from './Modal.vue';
const data = ref(null), page = ref(1), saving = ref(false), removing = ref(null), review = ref(''), error = ref('');
const sender = reactive({ kind: 'email', value: '', action: 'blocked', include_subdomains: false });
const suppression = reactive({ email: '', reason: 'manual', notes: '' });
async function load() { try { data.value = await api('mail-policy?page=' + page.value); } catch (e) { error.value = e.message; } }
async function save(kind, body) { saving.value = true; try { await api('mail-policy/' + kind, { method: kind === 'settings' ? 'PUT' : 'POST', body }); await load(); if (kind === 'senders') sender.value = ''; if (kind === 'suppressions') { suppression.email = ''; suppression.notes = ''; } notify('Mail policy saved'); } catch (e) { notify(e.message, true); } finally { saving.value = false; } }
function askRemove(kind, record) { removing.value = { kind, ...record }; review.value = ''; }
async function remove() { saving.value = true; try { await api('mail-policy/' + removing.value.kind + '/' + removing.value.id, { method: 'DELETE', body: { review: review.value } }); removing.value = null; await load(); notify('Restriction removed after review'); } catch (e) { notify(e.message, true); } finally { saving.value = false; } }
onMounted(load);
</script>
<template>
<p v-if="error" class="error-message">{{ error }}</p>
<div v-else-if="data" class="policy-settings">
<form class="settings-form" @submit.prevent="save('settings', data.settings)"><div class="section-intro"><span class="setting-icon"><Icon name="mail" /></span><div><h2>Delivery & account recovery</h2><p>Control open tracking and choose the mailbox used for password resets.</p></div></div>
<label class="check-label"><input type="checkbox" v-model="data.settings.track_opens" />Track email opens in outgoing ticket replies</label><p class="muted">Email opens indicate activity, not confirmed reading. Privacy services may register opens automatically, and some opens may not be recorded.</p>
<label>Password recovery mailbox<select v-model="data.settings.recovery_mailbox_id"><option :value="null">Disabled until a mailbox is selected</option><option v-for="box in state.workspace.mailboxes" :key="box.id" :value="box.id">{{ box.name }} · {{ box.sending_enabled ? 'Sending enabled' : 'Sending disabled' }}</option></select></label>
<p class="muted">Recovery works for existing accounts while registration is disabled. It obeys the global sending pause and recipient restrictions.</p>
<div class="info-banner"><Icon name="globe" /><p>Links use <strong>{{ data.public_url }}</strong>. For customers to open reset links, record email opens, and opt out, configure the application’s public HTTPS address in APP_URL.</p></div>
<button class="primary-button" :disabled="saving">Save email preferences</button></form>
<section class="policy-section"><div class="subsection-heading"><div><h2>Blocked & trusted senders</h2><p class="muted">Blocked mail is received into Spam. Exact email rules take priority over domain rules. Trust never overrides recipient suppression.</p></div></div>
<form class="form-stack policy-add" @submit.prevent="save('senders', sender)"><div class="form-grid"><label>Match<select v-model="sender.kind"><option value="email">Email address</option><option value="domain">Domain</option></select></label><label>{{ sender.kind === 'email' ? 'Email address' : 'Domain' }}<input v-model="sender.value" :type="sender.kind === 'email' ? 'email' : 'text'" :placeholder="sender.kind === 'email' ? 'person@example.com' : 'example.com'" required maxlength="255" /></label><label>Action<select v-model="sender.action"><option value="blocked">Block</option><option value="trusted">Trust</option></select></label></div><label v-if="sender.kind === 'domain'" class="check-label"><input type="checkbox" v-model="sender.include_subdomains" />Include subdomains</label><div><button class="secondary-button" :disabled="saving">Save sender rule</button></div></form>
<div v-for="rule in data.senders" :key="rule.id" class="management-row"><Icon :name="rule.action === 'blocked' ? 'spam' : 'check'" /><div class="management-row-main"><h3>{{ rule.value }}</h3><p>{{ rule.action }} · {{ rule.kind }}{{ rule.include_subdomains ? ' and subdomains' : '' }}</p></div><button class="text-button" @click="Object.assign(sender, rule)">Edit</button><button class="icon-button" @click="askRemove('senders', rule)" :aria-label="'Remove rule for ' + rule.value"><Icon name="trash" /></button></div><p v-if="!data.senders.length" class="muted">No sender rules yet.</p>
</section>
<section class="policy-section"><div class="subsection-heading"><div><h2>Suppressed recipients</h2><p class="muted">Complaints and confirmed opt-outs are added automatically. Suppression applies to the requester and CC recipients at send time.</p></div></div>
<form class="form-stack policy-add" @submit.prevent="save('suppressions', suppression)"><div class="form-grid"><label>Recipient email<input v-model="suppression.email" type="email" required /></label><label>Reason<select v-model="suppression.reason"><option value="manual">Manual stop</option><option value="complaint">Complaint</option><option value="opt_out">Opt-out</option><option value="hard_bounce">Hard bounce</option></select></label></div><label>Notes<input v-model="suppression.notes" maxlength="255" placeholder="Reason or evidence" /></label><div><button class="secondary-button" :disabled="saving">Suppress recipient</button></div></form>
<div v-for="item in data.suppressions.data" :key="item.id" class="management-row"><Icon name="lock" /><div class="management-row-main"><h3>{{ item.email }}</h3><p>{{ item.reason.replaceAll('_', ' ') }}{{ item.notes ? ' · ' + item.notes : '' }}</p></div><button class="text-button" @click="askRemove('suppressions', item)">Review & remove</button></div>
<p v-if="!data.suppressions.total" class="muted">No suppressed recipients.</p><div v-if="data.suppressions.last_page > 1" class="form-actions"><button class="secondary-button" :disabled="page === 1" @click="page--; load()">Previous</button><span>{{ page }} / {{ data.suppressions.last_page }}</span><button class="secondary-button" :disabled="page === data.suppressions.last_page" @click="page++; load()">Next</button></div>
</section></div>
<Modal v-if="removing" title="Review recipient restriction" @close="!saving && (removing = null)"><form class="form-stack" @submit.prevent="remove"><p>Remove the restriction for <strong>{{ removing.email || removing.value }}</strong>? For complaints and opt-outs, verify permission to resume email first.</p><label>Review notes<textarea v-model="review" required minlength="10" maxlength="160" rows="3" /></label><p class="muted">Existing suppressed replies remain unsent. Write a new reply after review.</p><div class="form-actions"><button class="primary-button" :disabled="saving || review.trim().length < 10">Remove restriction</button></div></form></Modal>
</template>
